### ISSUE TITLE
WinDivertOpen always return INVALID_HANDLE_VALUE

### ISSUE THREAD

**Issue by sheldonlyr** [stievie/pasdivert#2]
I use windows 10 64-bit, Delphi 10.1, WinDivert 1.1.8 binary distribution from the WinDivert homepage.
When i debug netdump project.
32-bit Windows debug: WinDivertOpen always return INVALID_HANDLE_VALUE, and GetLastError return ERROR_INVALID_PARAMETER.
64-bit Windows debug: WinDivertOpen return success.

**Comment by stievie** [comment]
These programs must be run with administrator privileges. When you debug the program with Delphi you must run Delphi as Administrator so the spanwed process also has administrator privileges. Do you run Delphi as Admin?

**Comment by sheldonlyr** [comment]
Yes, I run Delphi as Admin. I just replace priority parameter with number 0, then WinDivertOpen return ok, it's so strange...

**Comment by stievie** [comment]
Oh, that seems then to be a WinDivert issue and there is not much doc about the priority value.

**Comment by sheldonlyr** [comment]
I changed  INT16 = ShortInt to INT16 = SmallInt, now 32-bit debug ok!

**Comment by stievie** [comment]
Oh, that seems to be a bug, INT16 should be really a SmallInt and not a ShortInt. Thank you, Ill change that.
